GLOBAL_LIST_INIT(ID_access, list(
	list("ACCESS_SECURITY_LVL1", "ACCESS_SECURITY_LVL2", "ACCESS_SECURITY_LVL3", "ACCESS_SECURITY_LVL4", "ACCESS_SECURITY_LVL5"),
    list("ACCESS_SCIENCE_LVL1", "ACCESS_SCIENCE_LVL2", "ACCESS_SCIENCE_LVL3", "ACCESS_SCIENCE_LVL4", "ACCESS_SCIENCE_LVL5"),
    list("ACCESS_MEDICAL_LVL1", "ACCESS_MEDICAL_LVL2", "ACCESS_MEDICAL_LVL3", "ACCESS_MEDICAL_LVL4", "ACCESS_MEDICAL_LVL5"),
    list("ACCESS_ENGINEERING_LVL1", "ACCESS_ENGINEERING_LVL2", "ACCESS_ENGINEERING_LVL3", "ACCESS_ENGINEERING_LVL4", "ACCESS_ENGINEERING_LVL5"),
    list("ACCESS_ADMIN_LVL1", "ACCESS_ADMIN_LVL2", "ACCESS_ADMIN_LVL3", "ACCESS_ADMIN_LVL4", "ACCESS_ADMIN_LVL5")))
